### ISSUE TITLE
Отсутствует документация по сценариям

### ISSUE THREAD

**Issue by vpArth** [open-oncor/api-doc#1]
Файлы:

 - /docs/scripts/RegClinicalGroup/index.md (Перевод пациента из одной клинической группы в другую)
 - /docs/scripts/RegDeath/index.md (Регистрация смерти пациента)
 - /docs/scripts/newReferral/index.md (Формирование направлений)

Являются копиями:  
- /docs/scripts/RegOut/index.md (Снятие с учета пациента, ранее поставленного на учет)

**Comment by s-beaver** [comment]
Работаем над этим

**Comment by s-beaver** [comment]
Раздел сценарии обновлен

**Comment by vpArth** [comment]
Увидел. упростили до одной страницы. Так намного лучше, благодарю.
